services:
  website-rn:
    image: ghcr.io/reynario/website-rn:latest
    networks:
      - RNNet
    deploy:
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.website-rn.rule=Host(`rndigitalmidia.com.br`) || Host(`www.rndigitalmidia.com.br`)"
        - "traefik.http.routers.website-rn.entrypoints=websecure"
        - "traefik.http.routers.website-rn.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.website-rn.service=website-rn"
        - "traefik.http.services.website-rn.loadbalancer.server.port=80"

networks:
  RNNet:
    external: true
